### ISSUE TITLE
how to hide tooltip on click

### ISSUE THREAD

**Issue by naveedshahji** [drozhzhin-n-e/ng2-tooltip-directive#102]
how to remove tooltip on click element

**Comment by cosminv6u** [comment]
I'm trying https://gist.github.com/drozhzhin-n-e/46ebc7eb7db3c34ee8f97f0d6b483eb7 but still no luck

**Comment by cosminv6u** [comment]
Now I have an issue, I open the Tooltip with HOVER and when I try to close it with an X button, the .hide() doesn't do nothing.
If I open the Tooltip with CLICK, then .hide() works fine!

frustrating, please help. @drozhzhin-n-e

**Comment by drozhzhin-n-e** [comment]
@naveedshahji Use the `hide()` method. An example of a call on the project home page http://ivylab.space/tooltip in the Methods section.
