### ISSUE TITLE
Property content-type not used

### ISSUE THREAD

**Issue by AndreyKotofotoff** [drozhzhin-n-e/ng2-tooltip-directive#104]
Hello!
[tooltip.directive.ts](https://github.com/drozhzhin-n-e/ng2-tooltip-directive/blob/master/src/app/tooltip/tooltip.directive.ts#L48)
![image](https://user-images.githubusercontent.com/15908484/81375895-1fa81b80-910b-11ea-889e-65126b1384dd.png)

**Comment by drozhzhin-n-e** [comment]
Hey. I fixed it in version 2.9.22
