### ISSUE TITLE
Angular 9 (ivy) and [options] return Object Object

### ISSUE THREAD

**Issue by pixedd** [drozhzhin-n-e/ng2-tooltip-directive#105]
With Angular "~9.1.0" (ivy) and  "ng2-tooltip-directive": "^2.9.20", if we use content-type="template" and add [options] object, the tooltip is trigger but the content is: Object Object without any errors. If i remove the [options] property it's working fine.

Example:
`<ng-template #HtmlContent><p style="color:white;">Hello i'm a <strong>bold</strong> text</p></ng-template>`

`<span content-type="template" [options]="myOptions" [tooltip]="HtmlContent">
        Tooltip
</span>`

It was working properly before upgrading my project from Angular 8.X to Angular 9.1.X

**Comment by omygoodness** [comment]
Same here

**Comment by myemuk** [comment]
Try `contentType="template"` instead of `content-type="template"`

**Comment by pixedd** [comment]
@myemuk thanks for the advice but it's not working, same result: the tooltip is display with content: [Object Object]

**Comment by myemuk** [comment]
What happens if you remove `[options]="myOptions"`?

**Comment by pixedd** [comment]
@myemuk 

> If i remove the [options] property it's working fine.

**Comment by needsmorecoffee** [comment]
@pixedd you need to set "contentType: 'template'" in the options object rather than the template. Works for me when I do that.

**Comment by genru** [comment]
same environment same issue. I had tried @needsmorecoffee @myemuk 's solutions, no luck

**Comment by drozhzhin-n-e** [comment]
@pixedd @omygoodness @genru I fixed it in version 2.9.22

**Comment by sraza295** [comment]
@needsmorecoffee Thanks bro, you saved my day
