### ISSUE TITLE
No longer working with Angular 10

### ISSUE THREAD

**Issue by hadley8899** [drozhzhin-n-e/ng2-tooltip-directive#109]
Seems I cannot upgrade to angular 10 with this package installed.

The error produced from ng update is as follows 

user@rcomputer:~/dev/projects/user-portal$ ng update @angular/cli
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 62 dependencies.
Fetching dependency metadata from registry...
                  Package "ng2-tooltip-directive" has an incompatible peer dependency to "@angular/common" (requires "^7.2.0" (extended), would install "10.0.4").
                  Package "ng2-tooltip-directive" has an incompatible peer dependency to "@angular/core" (requires "^7.2.0" (extended), would install "10.0.4").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/tmp/ng-klRlsp/angular-errors.log" for further details.

**Comment by drozhzhin-n-e** [comment]
@hadley8899 Try to install the latest version of the library. It is built in ng10 environment.
