### ISSUE TITLE
add parentElement width and element position

### ISSUE THREAD

**Issue by rajeshK88** [drozhzhin-n-e/ng2-tooltip-directive#11]
Hi,
 can we add a input to the directive for taking parentElement width. This will help to take the position for parent element width.

getElemPosition(){
        this.elemPosition = this.elementRef.nativeElement.parentElement.getBoundingClientRect();
    }

let elemWidth = this.elementRef.nativeElement.parentElement.offsetWidth;

Let me know if it is possible..

**Comment by drozhzhin-n-e** [comment]
@rajeshK88 You can independently determine the width of the parent element and pass it in the `width` property. 

`<button tooltip="Parent width" [width]="parentWidth"></button>`
