### ISSUE TITLE
Strict type checking expecting theme boolean

### ISSUE THREAD

**Issue by s3nt1n3lz21** [drozhzhin-n-e/ng2-tooltip-directive#120]
With Angular 9 and strict type checking in templates on   

"angularCompilerOptions": {
    "strictTemplates": true,
    "strictInjectionParameters": true
  },

I'm getting a type error on the theme property. For some reason its expecting a type of Boolean but its should be expecting a string. Either "dark" or "light".

When I set theme="light"
I get the error:  Type 'string' is not assignable to type 'boolean'.

![image](https://user-images.githubusercontent.com/30151687/95453925-9e77dd80-0963-11eb-9625-50f8e4651b11.png)

Heres a simple reproducing example
https://stackblitz.com/edit/angular-tgnaby?file=src/app/app.component.html

**Comment by drozhzhin-n-e** [comment]
This has been fixed in the latest release.
