### ISSUE TITLE
 Badly Packaged Library -- Breaks AOT Compilation in Angualr 5

### ISSUE THREAD

**Issue by on3al** [drozhzhin-n-e/ng2-tooltip-directive#13]
Using this package in an ng-clii 1.63 generated angualr 5 project works fine, but it will not work with
ng serve -aot 
or ng build -prod production builds that use aot

I believe this is related to a breaking change in angular 5

[https://github.com/angular/angular-cli/issues/8284](https://github.com/angular/angular-cli/issues/8284)

The resulting error is:
````
Module build failed: Error: node_modules\ng2-tooltip-directive\lib\tooltip.directive.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23)
    at plugin.done.then (D:\dev\reloadersjournal\rj-client\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by danieltorrer** [comment]
Same issue here, ¿Did you find a fix @on3al ?

angular: 5.1.3
cli: 1.6.3

**Comment by on3al** [comment]
@danieltorrer - not for the this package. For my own project that was using it I just added added the file https://github.com/drozhzhin-n-e/ng2-tooltip-directive/blob/master/src/tooltip.directive.ts directly into my project rather than pulling it from npm until this is resolved.

**Comment by returnlytom** [comment]
Probably the same underlying issue as this: https://github.com/drozhzhin-n-e/ng2-tooltip-directive/issues/5

As a workaround, I also just copied the directive code into our project; would prefer to use `npm` of course :)

**Comment by danieltorrer** [comment]
Thanks, it worked!
