### ISSUE TITLE
Feature - Added function to open tooltip with click

### ISSUE THREAD

**Issue by danieltorrer** [drozhzhin-n-e/ng2-tooltip-directive#14]
I modified the code a little bit to open a tooltip with a click instead of hovering the element.
Is it something you guys are interested in? I can PR the code if so.

Thanks for the library :)

**Comment by returnlytom** [comment]
Yeah that would be great, can you open a PR? 

Ideally the default behavior would remain unchanged, and the click would be opt-in.

**Comment by danieltorrer** [comment]
Done!
