### ISSUE TITLE
PRO version Installed but basic options are not working

### ISSUE THREAD

**Issue by thesaiprathap** [drozhzhin-n-e/ng2-tooltip-directive#144]
Hello,
I've purchased the pro version. I placed this in my app.module.ts file:
import { TooltipModule } from './components/tooltip/';
But basic version options are not working. How to use basic version options?

**Comment by drozhzhin-n-e** [comment]
Hello. What options do you mean exactly?

**Comment by thesaiprathap** [comment]
All options are not available. I don't know what's wrong I am doing.

**Comment by drozhzhin-n-e** [comment]
Do you have any errors in the console?

**Comment by thesaiprathap** [comment]
No there are no errors in the console

**Comment by drozhzhin-n-e** [comment]
OK. The tooltip appears, but some functions do not work, do I understand correctly? Or is the tooltip not displayed at all?

**Comment by thesaiprathap** [comment]
Yah.. Tooltip is working but some functions are not working.

**Comment by drozhzhin-n-e** [comment]
Give me time to check it out.

**Comment by thesaiprathap** [comment]
Sure....
Thank you so much for your support...

**Comment by drozhzhin-n-e** [comment]
Could you please give an example of your code where you are using the tooltip?

**Comment by drozhzhin-n-e** [comment]
Most likely the problem is in the names of the properties. They were renamed in the Pro version in CamelCase notation. I will update the documentation on the site soon.

**Comment by thesaiprathap** [comment]
F:\xxxx\xxxxx\xxxxx\src\app\components\tooltip

import { TooltipModule } from './components/tooltip/';

@NgModule({
     imports: [
       TooltipModule,
    ]
)}

<span placement="bottom" tooltip="Tooltip">Hover Here</span>

Anything need to add more or import?

I am trying to add a class using tooltip-class but it's not working...

**Comment by drozhzhin-n-e** [comment]
You imported correctly. I have updated the documentation, please see the updated property names.

**Comment by drozhzhin-n-e** [comment]
An update to the Pro version was published today, which fixes compatibility issues with the basic version functions. I recommend installing it.
