### ISSUE TITLE
Not working with Angular 6

### ISSUE THREAD

**Issue by Bram77** [drozhzhin-n-e/ng2-tooltip-directive#17]
After upgrading from Angular 5 to Angular 6 this directive stopped working. All I see in the log is dat it depends on specific (older) module versions. This was already the case when using Angular 5 and there the tooltips worked fine. Is there anything I can do to make de directive work with Angular 6?

**Comment by drozhzhin-n-e** [comment]
@Bram77 please try version 2.1.5
