### ISSUE TITLE
After --Prod build its giving error No component factory found for c. Did you add it to @NgModule.entryComponents?

### ISSUE THREAD

**Issue by shayanpaul** [drozhzhin-n-e/ng2-tooltip-directive#18]
After --Prod build, when i am trying to hovering on something that has the tooltip in it , its giving error No component factory found for c. Did you add it to @NgModule.entryComponents? followed by Cannot read property 'instance' of undefined.

I have just imported it in the module in app.module.ts file and added it in imports array. 
Working fine when not doing prod build.

**Comment by shayanpaul** [comment]
No this issue has not been resolved by importing it in app.module.ts. Any update on this issue. Prod build is something very essential for production

**Comment by drozhzhin-n-e** [comment]
@shayanpaul please try version 2.1.5

**Comment by panagulis72** [comment]
Someone found solution?...

**Comment by drozhzhin-n-e** [comment]
in which version of angular does the problem occur? Build with CLI?

**Comment by shayanpaul** [comment]
Seems like the latest version does not have this issue.. Cheers...

**Comment by panagulis72** [comment]
While building I have no error but when I open the application I get the error: 

> No component factory found for TooltipComponent. Did you add it to @NgModule.entryComponents?

I'm using this in package.json: "ng2-tooltip-directive": "^2.1.4"
And this version of angular:   
   "@angular/cdk": "^6.3.3",
    "@angular/common": "^6.0.7",
    "@angular/compiler": "^6.0.7",
    "@angular/core": "^6.0.7",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/forms": "^6.0.7",
    "@angular/http": "^6.0.7",
    "@angular/platform-browser": "^6.0.7",
    "@angular/platform-browser-dynamic": "^6.0.7

**Comment by drozhzhin-n-e** [comment]
@panagulis72 try 2.1.5, the latest version is packed in another way
