### ISSUE TITLE
bug: the tooltip doesn't disappear in a case

### ISSUE THREAD

**Issue by bentom12** [drozhzhin-n-e/ng2-tooltip-directive#20]
bug: if the tooltip is shown and the related dom element is destroyed/removed (ie. the page changes) then the tooltip remains fixed and cannot be removed anymore.

proposed fix: add "this.destroyTooltip();" in the "ngOnDestroy()" method.

**Comment by drozhzhin-n-e** [comment]
it seems I hurried to close the issue

**Comment by returnlytom** [comment]
Could this be related? LMK if a more detailed stack trace would be helpful in troubleshooting.

![tooltip_error](https://user-images.githubusercontent.com/22224829/45242579-7362c180-b2a5-11e8-8f4d-68237f281f45.png)

**Comment by kpodemski** [comment]
Hey @drozhzhin-n-e 

any news on this issue? at this moment tooltips has been always displayed, even tho application changed its route to another one x_x

**Comment by drozhzhin-n-e** [comment]
@kpodemski Hi. Try this one https://github.com/drozhzhin-n-e/ng2-tooltip-directive/commit/5807d6390ba31cfd47f2d32c84831ed81e47f8ff

**Comment by bdlaureano** [comment]
> > @kpodemski Hi. Try this one [5807d63](https://github.com/drozhzhin-n-e/ng2-tooltip-directive/commit/5807d6390ba31cfd47f2d32c84831ed81e47f8ff)
> 
> This appears to resolve the issue - any chance of a new release?

???

**Comment by jeremyng5352** [comment]
Hi there, 

May I know how can I fix this as a user, or this can only be fixed internally. Sorry, I am still quite a beginner on this.

**Comment by aharms24** [comment]
This bug is still persisting. The developer should not have to add code in the onDestroy method to make the tooltip disappear when navigating away. This is a great directive with a big flaw.

**Comment by drozhzhin-n-e** [comment]
I updated the npm library, try version 2.1.6
