### ISSUE TITLE
Allow to pass coordinates for positioning

### ISSUE THREAD

**Issue by dgroh** [drozhzhin-n-e/ng2-tooltip-directive#21]
Currently it's not possible to pass coordinates for positioning the tooltip. This can be useful when you have for instance a map (like googlemaps), but want the tooltip to sticky to the current clicked element on the map when moving the map around.

Example: http://jsfiddle.net/goredwards/2cs4puaz/

**Comment by drozhzhin-n-e** [comment]
Now you can set the tooltip coordinates using the position property. 

`<button tooltip="Custom position" placement="bottom" [position]="{top: 0, left: 200}">Custom position</button>`
