### ISSUE TITLE
Tooltip extends page height

### ISSUE THREAD

**Issue by kurthamilton** [drozhzhin-n-e/ng2-tooltip-directive#23]
The tooltip extends the page height before the position is applied. 

This is noticeable in Firefox, as the tooltip element is added first on element hover, and then the position applied when hovering over the text content. The effect isn't noticeable in Chrome since the position is calculated immediately.

This has the undesirable effect of causing the scroll bar to briefly appear when the addition of the unpositioned tooltip element causes the height of the page content to extend beyond the viewport.

I am using Angular 6.04, Firefox 61.0.2, Chrome 68.0.3440.106

**Comment by bernester** [comment]
will this be fixed?

**Comment by kurthamilton** [comment]
I'm now using ng-bootstrap in preference to individual libraries like this. It is well supported and kept up to date with Bootstrap releases.

[https://ng-bootstrap.github.io](https://ng-bootstrap.github.io)

Tooltip documentation: [https://ng-bootstrap.github.io/#/components/tooltip/examples](https://ng-bootstrap.github.io/#/components/tooltip/examples)

**Comment by drozhzhin-n-e** [comment]
Can you describe how to recreate the problem?
