### ISSUE TITLE
Please add maxWidth option

### ISSUE THREAD

**Issue by mikestotik** [drozhzhin-n-e/ng2-tooltip-directive#24]
<img width="201" alt="1" src="https://user-images.githubusercontent.com/31506160/44307203-cc29f300-a3a6-11e8-82f8-ee42114c6bd4.png">

**Comment by drozhzhin-n-e** [comment]
Added option `max-width: string `

https://github.com/drozhzhin-n-e/ng2-tooltip-directive/commit/8cbe87cba775af6fce7d13647529adaf60ee4983

**Comment by mikestotik** [comment]
Awesome! thank you very much!
