### ISSUE TITLE
style arrow

### ISSUE THREAD

**Issue by bdlaureano** [drozhzhin-n-e/ng2-tooltip-directive#25]
Hello,
I was able to style the box, but no the arrow, any idea?
Thank you!

**Comment by drozhzhin-n-e** [comment]
@bdlaureano  if I get you right. Style arrow depends on the pseudo-element ":after"

https://github.com/drozhzhin-n-e/ng2-tooltip-directive/blob/master/src/app/tooltip/tooltip.component.sass#L25

**Comment by bonomiandreia** [comment]
Hey! I know its too late to comment something, but in case of anyone wants...
 in style.scss:
```
.tooltip::after { 
  border-left: 5px solid transparent !important;
  border-right: 5px solid transparent !important;
  border-top: 5px solid #FFFFFF !important;
}
```

**Comment by bdlaureano** [comment]
Thank you!!! @bonomiandreia
