### ISSUE TITLE
Adding tooltip-class option not working

### ISSUE THREAD

**Issue by evalaidc** [drozhzhin-n-e/ng2-tooltip-directive#28]
I'm trying to add a tooltip class using the options. It doesn't appear to be taking the class "new-tooltip-class"
```
// in html
<span tooltip="Here is the tooltip text" [options]="tooltipOptions" >
   Show Tool Tip
                </span>
```
```
// in controller.ts
  tooltipOptions = {
    'placement': 'left',
    'show-delay': '500',
    'tooltip-class': 'new-tooltip-class'
  };
```

I'm trying to change the styles of the tooltip using this newly added class.  (for instance change the background-color: red)

**Comment by drozhzhin-n-e** [comment]
Are you sure? I checked your code and found no problem

![screen](https://user-images.githubusercontent.com/6724565/45919951-410cb300-bea6-11e8-8028-7b9dfd969b99.png)

**Comment by rochapablo** [comment]
The class it's been add, but nothing changes.

```
tooltip-class="tooltip-feedback"
```

```
.tooltip-feedback {
  background-color: red;
}
```

```
"@angular": "^6.1.0",
"ng2-tooltip-directive": "^2.1.5",
```

**Comment by drozhzhin-n-e** [comment]
@rochapablo Are you using a global stylesheet?

**Comment by shaukath** [comment]
**Not Working For me**
I tried with !important also
In the same component css i have added the class, and the same class added to myOptions tooltip-class: "tooltip_bg"
"@angular": "7.2.12",
"ng2-tooltip-directive": "^2.1.9",

.tooltip_bg {
background-color: green !important;
}

Didn't worked for me, Kindly help me

**Comment by drozhzhin-n-e** [comment]
@shaukath class tooltip_bg added to the tooltip tag? Have you added a CSS to a component style file or to a global style file?

**Comment by shaukath** [comment]
I tried in both didn't get.
::ng-deep with the custom class solved my issue.

and with ::ng-deep .tooltip also we can customise the tooltip CSS.
