### ISSUE TITLE
Hide tooltip from component.ts

### ISSUE THREAD

**Issue by panagulis72** [drozhzhin-n-e/ng2-tooltip-directive#29]
Hi,
is that possible to retrieve an instance of a Tooltip into the component.ts, to close the tooltip manually with hide() function?

**Comment by drozhzhin-n-e** [comment]
@panagulis72 hello, see the example here https://github.com/drozhzhin-n-e/ng2-tooltip-directive/blob/master/src/app/app.component.html#L71

**Comment by panagulis72** [comment]
Hi @drozhzhin-n-e , yes I found that example before, but there alla done in the HTML dom; is there a way to do it from the Typscript code?

**Comment by drozhzhin-n-e** [comment]
@panagulis72 yes, exactly the same: https://gist.github.com/drozhzhin-n-e/5511e3d2c1b59d9403edf7e882b36667 

`this.someTooltip.hide()`

**Comment by panagulis72** [comment]
Perfect, now it works fine! Thank you very much for the quick support!
