### ISSUE TITLE
ERROR in Metadata version mismatch for module 'ng2-tooltip-directive.d.ts', found version 4, expected 3

### ISSUE THREAD

**Issue by kashifnazar** [drozhzhin-n-e/ng2-tooltip-directive#34]
Initially, I didn't get any errors after I installed this library and used it in my project. Next day, when I tried to  start the server, I started getting the following error message.

ERROR in Metadata version mismatch for module <project_path>/node_modules/ng2-tooltip-directive/ng2-tooltip-directive.d.ts, found version 4, expected 3.

Here is the version info.
```
@angular/cli: 1.3.2
node: 8.11.2os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6@angular/compiler: 4.3.6@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/platform-server: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
```

**Comment by dgonz371** [comment]
Try downgrading to version 2.0.0 of the ng2-tooltip-directive

**Comment by Kuldevsingh** [comment]
> Initially, I didn't get any errors after I installed this library and used it in my project. Next day, when I tried to start the server, I started getting the following error message.
> 
> ERROR in Metadata version mismatch for module <project_path>/node_modules/ng2-tooltip-directive/ng2-tooltip-directive.d.ts, found version 4, expected 3.
> 
> Here is the version info.
> 
> ```
> @angular/cli: 1.3.2
> node: 8.11.2os: win32 x64
> @angular/animations: 4.3.6
> @angular/common: 4.3.6@angular/compiler: 4.3.6@angular/core: 4.3.6
> @angular/forms: 4.3.6
> @angular/http: 4.3.6
> @angular/platform-browser: 4.3.6
> @angular/platform-browser-dynamic: 4.3.6
> @angular/platform-server: 4.3.6
> @angular/router: 4.3.6
> @angular/cli: 1.3.2
> @angular/compiler-cli: 4.3.6
> @angular/language-service: 4.3.6
> ```
 Hi, 
I having same issue did you find any solution so far ?
