### ISSUE TITLE
Line break for tooltip

### ISSUE THREAD

**Issue by jeremyng5352** [drozhzhin-n-e/ng2-tooltip-directive#35]
Feature request: Able to take in <br/> or \n in for the tooltip. 
For example: tooltip="click to open menu \n drag to move item"

**Comment by shubh9415** [comment]
is there a way to break line for now?

**Comment by usuf13** [comment]
> is there a way to break line for now?

I'm used '\n' and it works for 2.1.5 / angular 7

**Comment by sovicheacheth** [comment]
'\n' is not working for me on 2.1.6 and angular 6.2.4

**Comment by drozhzhin-n-e** [comment]
Now you can use HTML tags `tooltip="click to open menu <br /> drag to move item"`
