### ISSUE TITLE
Tooltip is displayed on mobile despite display-mobile option being set to false

### ISSUE THREAD

**Issue by oloflandahl** [drozhzhin-n-e/ng2-tooltip-directive#36]
The displayMobile setter only sets value if it's truthy, hence false cannot be set:

if (value) {
  this._options['display-mobile'] = value;
}

**Comment by kexxxfeng** [comment]
Use another way 
```ts
myOptions = {
    'placement': 'left',
    'display-mobile': false
}
```
```html
<span tooltip="Tooltip" [options]="myOptions">Tooltip on left</span>
```

**Comment by drozhzhin-n-e** [comment]
@oloflandahl fixed https://github.com/drozhzhin-n-e/ng2-tooltip-directive/commit/da8bfa34f23070272879fa7e3c0f3ea69dceeeb5
