### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by rajesh9v** [drozhzhin-n-e/ng2-tooltip-directive#4]
![image](https://user-images.githubusercontent.com/8220618/27435910-2c97c06a-577b-11e7-96a9-e00b79fa9fc2.png)

**Comment by sarathkcm** [comment]
I am getting the same error

**Comment by sarathkcm** [comment]
Works perfectly in Chrome though... @drozhzhin-n-e, could you please check the issue?

**Comment by drozhzhin-n-e** [comment]
This is fixed in the last commit
