### ISSUE TITLE
Question: it seems hide-delay config option is not working

### ISSUE THREAD

**Issue by karandashek** [drozhzhin-n-e/ng2-tooltip-directive#41]
Hi! I'm trying to set "hide-delay" value as 0, but nothing changes and i'm not sure why. Some different options in the same config are working correctly('placement' and 'animation-duration'). Hope you can help me :) Is there any way to hide tooltip immediately after pointer moved away from element?
Thanks!

**Comment by drozhzhin-n-e** [comment]
Hi. Try setting 0 for 'animation-duration'. This is the time for animation. 'hide-delay' starts after 'animation-duration'.

**Comment by karandashek** [comment]
Set 
'animation-duration': 0,
'hide-delay': 0

but nothing changed, tooltip appears immediately and disappears with delay

**Comment by drozhzhin-n-e** [comment]
I think the problem is in the `[options]` property. Try this:

```
<button 
	tooltip="Tooltip"
	hide-delay="0" 
	placement="top">Tooltip on top</button>
```

**Comment by karandashek** [comment]
Yes, you are right, i used hide-delay="0" separately and it works perfect! 
Thank you!
