### ISSUE TITLE
add html in the tooltip

### ISSUE THREAD

**Issue by jordibaliellas** [drozhzhin-n-e/ng2-tooltip-directive#43]
How can i pass html to tooltip?

**Comment by drozhzhin-n-e** [comment]
there is no html support now

**Comment by nirajkrz** [comment]
You can pass it.. I modified it to do it like this:

In ToolTipComponet template:
`<div *ngIf="valueType === 'html' else noHtml" [innerHTML]="value"></div>
<ng-template #noHtml>{{value}}</ng-template>` 

and pass the valueType as part of tool-tip configuration: when you need the HTML display, just use like this:

` <div tooltip="{{getHTML()}}" placement="top" value-type="html">`

**Comment by nirajkrz** [comment]
@drozhzhin-n-e , i can work on this and create a PR if you would like to. Let me know what you think

**Comment by nirajkrz** [comment]
> there is no html support now

@drozhzhin-n-e , i will be happy to work on this and create a PR if you would like to. Let me know what you think

**Comment by drozhzhin-n-e** [comment]
@nirajkrz thanks for the idea. I will definitely do it when I have free time.

**Comment by returnlytom** [comment]
@drozhzhin-n-e This can be closed now that #51 has been merged.

Also, can you bump the version in npm?

**Comment by drozhzhin-n-e** [comment]
@returnlytom @jordibaliellas  added to version 2.1.9
