### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'button'.

### ISSUE THREAD

**Issue by vitarunaeva** [drozhzhin-n-e/ng2-tooltip-directive#48]
<button md-icon-button tooltip="tooltipText" [options]="tooltipOptions">

**Comment by drozhzhin-n-e** [comment]
Make sure the tooltip works without `[options]`.  And also check `<button tooltip = "tooltipText" [options] = "tooltipOptions">`.

**Comment by vitarunaeva** [comment]
I sure the tooltip works without [options]. Version 2.0.0 provides this functionality?

**Comment by drozhzhin-n-e** [comment]
@vitarunaeva no, [options] is in later versions

**Comment by vitarunaeva** [comment]
@drozhzhin-n-e ok.  I use "@angular/material": "2.0.0-beta.10" . But, versions "@angular/material": "2.0.0-beta.10" and "ng2-tooltip-directive": "^2.1.6" aren`t compatible (ERROR in Metadata version mismatch for module 'ng2-tooltip-directive.d.ts', found version 4, expected 3). I lowered the version of your package to 2.0.0. How can I set default tooltip properties in one place? Maybe using a method TooltipModule.forRoot(...) in `@NgModule({imports: ...})` .

**Comment by drozhzhin-n-e** [comment]
@vitarunaeva Take the module from the repository. This is a link to version 2.0.0: https://github.com/drozhzhin-n-e/ng2-tooltip-directive/tree/08b101b04170eb2b6d6c572780e7da5bbe8b4bb5 

Change `tooltip.directive.ts`:
```
  @Input('tooltip') tooltipValue: string = '';
  @Input() placement: string = 'top';
  @Input() delay: number = 0;
  @Input('hide-delay-mobile') hideDelayMobile: number = 1500;
  @Input('z-index') zIndex: number = 0;
  @Input('animation-duration') animationDuration: number = 300;
  @Input() trigger: string = 'hover';
```

Set default values here.
