### ISSUE TITLE
AoT compilation: Directive TooltipDirective, Expected 0 arguments, but got 1.

### ISSUE THREAD

**Issue by cherurg** [drozhzhin-n-e/ng2-tooltip-directive#49]
I get this error when try to compile my library that has `ng2-tooltip-directive` dependency. Please, consider adding argument `event: any` here: https://github.com/drozhzhin-n-e/ng2-tooltip-directive/blob/02b615545af5dafd0fd39f27ed9501db0a4a072b/src/app/tooltip/tooltip.directive.ts#L212

Another option is removing of the second argument `['$event']` from the decorator: https://github.com/drozhzhin-n-e/ng2-tooltip-directive/blob/02b615545af5dafd0fd39f27ed9501db0a4a072b/src/app/tooltip/tooltip.directive.ts#L211

P.S. thank you for your work.

**Comment by drozhzhin-n-e** [comment]
@cherurg fixed in version 2.1.8

**Comment by cherurg** [comment]
@drozhzhin-n-e thank you!
