### ISSUE TITLE
You should not need to recompile .ts files in node_modules

### ISSUE THREAD

**Issue by sarathkcm** [drozhzhin-n-e/ng2-tooltip-directive#5]
Hello,
Happen to come across this compiler error while using your directive. 

> ERROR in <dir>/node_modules/ng2-tooltip-directive/lib/tooltip.directive.ts
> Module build failed: Error: Typescript emitted no output for <dir>\node_modules\ng2-tooltip-directive\lib\tooltip.directive.ts.
> You should not need to recompile .ts files in node_modules.
> 
> Please contact the package author to advise them to use --declaration --outDir.
> More https://github.com/Microsoft/TypeScript/issues/12358

For the time being, I included the node_modules folder in compile paths and it worked fine.

**Comment by returnlytom** [comment]
Would this require changes to the `package.json`? Also affected by this, ended up copy-and-pasting the directive code into my own project
