### ISSUE TITLE
I think the component should be able to expose a custom fetch location API based on the mouse hovering over the target element for a while.

### ISSUE THREAD

**Issue by anlovedota1** [drozhzhin-n-e/ng2-tooltip-directive#54]
I think the component should be able to expose a custom fetch location API based on the mouse hovering over the target element for a while.

**Comment by drozhzhin-n-e** [comment]
@anlovedota1  in the latest version of tooltips, events have the "position" property https://github.com/drozhzhin-n-e/ng2-tooltip-directive#events
