### ISSUE TITLE
can we show the tootltip on bottom-right and can we change the font-size of the tooltip

### ISSUE THREAD

**Issue by naveedshahji** [drozhzhin-n-e/ng2-tooltip-directive#59]
can we show the tootltip on bottom-right and can we change the font-size of the tooltip

**Comment by drozhzhin-n-e** [comment]
@naveedshahji The tooltip has only four positions: "top", "bottom", "left", "right". To change the tooltip style, use the global stylesheet: https://github.com/drozhzhin-n-e/ng2-tooltip-directive/issues/61
