### ISSUE TITLE
Set default values for tooltip

### ISSUE THREAD

**Issue by Leonard590** [drozhzhin-n-e/ng2-tooltip-directive#60]
Hi,

is there a way to set the default settings?
For example I'd like to set `show-delay` to a default value of 300.
It seems cumbersome to add that option to every single tooltip in the application.

Kind regards

**Comment by drozhzhin-n-e** [comment]
@Leonard590 hi, look an example here:

https://github.com/drozhzhin-n-e/ng2-tooltip-directive#set-default-values
