### ISSUE TITLE
how to set custom font for tooltip?

### ISSUE THREAD

**Issue by digish777** [drozhzhin-n-e/ng2-tooltip-directive#61]
how to set custom font for tooltip?

**Comment by levz0r** [comment]
Great question! We were wondering too...

**Comment by cosgab** [comment]
Any news?

**Comment by drozhzhin-n-e** [comment]
@digish777 @levz0r @cosgab  use the global stylesheet (src/styles.scss). For example:
```
tooltip {
  font-family: monospace;
}
```
