### ISSUE TITLE
add new line in the tool tip

### ISSUE THREAD

**Issue by digish777** [drozhzhin-n-e/ng2-tooltip-directive#62]
add new line in the tool tip

**Comment by MusicDev33** [comment]
To do this, you'll want to use HTML to style the tooltip. Say you have a span element that you want a multi-line tooltip for. The following line would make it multi-line:
```
<span>tooltip="<p>Hello I'm <br> text!</p>"</span>
```
The `<br>` tag specifies a line break in HTML.
