### ISSUE TITLE
How to increase width of tooltip?

### ISSUE THREAD

**Issue by helen31** [drozhzhin-n-e/ng2-tooltip-directive#63]

**Comment by DoKraus** [comment]
Was not able to put a custom-class on the tooltip, but

```
/deep/ tooltip {
  max-width: calc(100vw / 2 - 50px) !important;
}
```

works for me at the moment (the default `max-width` is `200px`).

**Comment by helen31** [comment]
Thanks

**Comment by rafaelsinosak** [comment]
thanks!

**Comment by drozhzhin-n-e** [comment]
you can use max-width property

`<button tooltip="Maximum width 300 pixels" [max-width]="300"></button>`

**Comment by drozhzhin-n-e** [comment]
`max-width` works in version 2.2.9+
