### ISSUE TITLE
Tool-tip Position in an Angular material dialog

### ISSUE THREAD

**Issue by am-awais** [drozhzhin-n-e/ng2-tooltip-directive#68]
I am using it with Angular material and some time when i open a material dialog and open tool-tip it displace its original position i.e
placement= top but it shows on out side the dialog modal on top like so much space between tool-tip and tool-tip element. it happens in all Browser but randomly
Please Help (as this is the tool-tip which fits for my project)

**Comment by am-awais** [comment]
@drozhzhin-n-e  
Sure As i told you it happen's sometimes so when ever i am able to capture that will show you.

**Comment by am-awais** [comment]
Bug(currently i manage to record that in safari but it happens in all browsers often)
screenshot:
https://www.screencast.com/t/3auGUq2uu8n

Recording:
https://www.screencast.com/t/njSGA6EsF

**Comment by drozhzhin-n-e** [comment]
@am-awais I think you need to try to solve this problem yourself. I don’t have time now to look for a solution, but I can make an assumption. Get the last commit from this repository. If this does not help, try setting the coordinates of the tooltip using the `position` property.

**Comment by am-awais** [comment]
@drozhzhin-n-e
I know i need to solve it my self, i used position property but same thing happen and all files are latest.
Anyway thanks for your precious time

**Comment by drozhzhin-n-e** [comment]
@am-awais I couldn’t see the video that you attached because of a flash player error. Try to get the coordinates of the button that opens the tooltip at different points in time of opening the modal window. If you manage to get the correct coordinates of the button, then use them, or write here the method by which you received them.

**Comment by am-awais** [comment]
ok one more thing by using the coordinates is it responsive as well? because coordinates changes as browser screen size vary

**Comment by drozhzhin-n-e** [comment]
@am-awais I meant that you can get the coordinates of an element, for example using the `Element.getBoundingClientRect()` method. The `position` property does not yet respond to resizing the browser window and scrolling.
