### ISSUE TITLE
Doesn't work on disabled element?

### ISSUE THREAD

**Issue by donp-kitcheck** [drozhzhin-n-e/ng2-tooltip-directive#69]
When I apply the directive to a `<button>` element that has either the `disabled` attribute or a CSS property of `pointer-events: none`, then the tooltip won't be shown.  It seems like the display of the tooltip is dependent on the cursor being in a normal state, and not any state that would be associated with a disabled element.

That's a problem, because there's a common use case of needing to display a tooltip for a disabled element, to explain *why* the element is disabled.

Is this something that any option on this directive can control, to enable the display?

**Comment by drozhzhin-n-e** [comment]
@donp-kitcheck I did not find a way to get mouse events on a disabled button. Try using `class="disabled"` instead of the `disabled` property and add CSS properties for this class.

https://stackoverflow.com/questions/16109228/clicking-a-disabled-input-or-button/16109366

**Comment by xKelvin** [comment]
You can also wrap another element around it!
I.e.:

```html
<span style="display: inline-block" tooltip="I'm disabled!">
    <button type="submit" disabled>Save</button>
</span>
```
