### ISSUE TITLE
The tooltip is not deleted if the main element was deleted.

### ISSUE THREAD

**Issue by makito** [drozhzhin-n-e/ng2-tooltip-directive#7]
If the element on which the tooltip directive is applied is removed from dom, then the tooltip, if it was previously shown, is not deleted.
To fix this, you need to add the decorator @HostListener ("mousedown") to the method of hiding the tooltip.
Sorry, but I can not create a pull request.

**Comment by giuseppeminnella** [comment]
fyi: https://github.com/drozhzhin-n-e/ng2-tooltip-directive/pull/9
