### ISSUE TITLE
Auto placement option

### ISSUE THREAD

**Issue by wmamunhossain** [drozhzhin-n-e/ng2-tooltip-directive#71]
I don't want to set the placement. When the button is close to any edge of the view, the tooltip content of that button goes outside of the visibility. I can't manually set it because I am using it as a standard component all over my app dynamically.

**Comment by drozhzhin-n-e** [comment]
Do you have any idea how to do this?

**Comment by drozhzhin-n-e** [comment]
@wmamunhossain I updated your idea. Auto-positioning should always be on, but you need to be able to set priority positioning.

**Comment by wmamunhossain** [comment]
@drozhzhin-n-e Thanks, Could you please publish the package?

**Comment by drozhzhin-n-e** [comment]
@wmamunhossain  I published the package
