### ISSUE TITLE
`ng-template` support doesn't working after version  2.1.9

### ISSUE THREAD

**Issue by wmamunhossain** [drozhzhin-n-e/ng2-tooltip-directive#74]
I was trying to use the following approach to show the tooltip.
```
<ng-template #HtmlContent>
  <p>Hello i'm a <strong>bold</strong> text!</p>
</ng-template>
 
<span [tooltip]="HtmlContent" content-type="template">
  Tooltip with template content
</span>
```
But it's not working after taking the update to latest version from `2.1.9`.  It shows like this.
![Untitled](https://user-images.githubusercontent.com/9004837/65390189-ac6db700-dd7e-11e9-8e48-bbe3887d26ca.png)

**Comment by drozhzhin-n-e** [comment]
@wmamunhossain Fixed in version 2.7.15
