### ISSUE TITLE
position	{top: number, left: number} not working in Angular 4.1.3

### ISSUE THREAD

**Issue by rabinsonrajendran** [drozhzhin-n-e/ng2-tooltip-directive#78]
Screen Shot:
![tool](https://user-images.githubusercontent.com/40715645/68195727-588cf980-ffdd-11e9-96d9-7fc0d7b83581.JPG)
HTML code: 
`<div class="" placement='top' [position]="{ top: 10, left: 500}" tooltip="{{ toolTipText }}">{{ toolTipT }}</div>`

**Comment by drozhzhin-n-e** [comment]
@rabinsonrajendran Are you sure you are using the latest version of the module?

**Comment by rabinsonrajendran** [comment]
@drozhzhin-n-e,  I'm using Angular "4.1.3" and "ng2-tooltip-directive": "^2.1.7"

**Comment by drozhzhin-n-e** [comment]
@rabinsonrajendran the position property is available only in new versions
