### ISSUE TITLE
apparently not working with angular 4

### ISSUE THREAD

**Issue by phil123456** [drozhzhin-n-e/ng2-tooltip-directive#8]
Hello

tried to add it to my project, no tooltip ever appears

**Comment by returnlytom** [comment]
Works for us on 4.2.x; however because of https://github.com/drozhzhin-n-e/ng2-tooltip-directive/issues/5 we ended up copying and pasting the directive code directly into our repo

**Comment by KissBalazs** [comment]
This is not working for me either. (angular 4.3.1)

After a bit debugging, what I saw is that in the `show()` method:

`if (this.showTimeoutId) {
      clearTimeout(this.showTimeoutId);
    }

    this.showDelay = this.delay || this.showDelay;
    this.showTimeoutId = setTimeout(() => {
      if (this.tooltip){
        this.tooltip.className += " ng-tooltip-show";
      }
    }, this.showDelay);`

in the lambda method, the `this.tooltip` is undefined. I am not sure why, but replacing this with the direct
`    this.tooltip.className += " ng-tooltip-show"; ` doesn't solve it either. Maybe this helps, but sadly currently I do not have the time to investigate this further.

**Comment by akshay-gupta5606** [comment]
Do we have a solution for this ?

**Comment by akshay-gupta5606** [comment]
There is no tooltip displayed.The style is displayed-:
<span placement="top" ng-reflect-tooltip-text="Tooltip" ng-reflect-placement="top">HIIII</span>
But the tooltip is not displayed.I can see the text is also assigned but the tooltip does not popup
