### ISSUE TITLE
tooltip-class

### ISSUE THREAD

**Issue by JaviLopezM** [drozhzhin-n-e/ng2-tooltip-directive#86]
Its possible to define more than 1 class in tooltip-class param? 
If its possible, how to separate the diferent classes?

**Comment by fdarveau** [comment]
Until #47 finally gets merged, multiple classes is not supported by this plugin.

**Comment by drozhzhin-n-e** [comment]
@JaviLopezM You need to update the library to the latest version. To add multiple classes, separate them with a space: `tooltip-class="test test2"`
